// <auto-generated />
using System;
using System.Collections.Generic;
using AI_BE.Data;
using AI_BE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI_BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316135044_AddPasswordResetTokens")]
    partial class AddPasswordResetTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI_BE.Models.Attempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("RecordMotionData")
                        .HasColumnType("jsonb");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SignId")
                        .HasColumnType("integer");

                    b.Property<string>("SignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SignId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("AI_BE.Models.Learner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("AI_BE.Models.LessonSign", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("SignName")
                        .HasColumnType("text");

                    b.HasKey("LessonId", "SignName");

                    b.ToTable("LessonSigns");
                });

            modelBuilder.Entity("AI_BE.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("AI_BE.Models.PracticeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PassRate")
                        .HasColumnType("numeric");

                    b.Property<int>("PassedSigns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalSigns")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("LessonId");

                    b.ToTable("PracticeSessions");
                });

            modelBuilder.Entity("AI_BE.Models.SignSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<List<Landmark>>("Landmarks")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SignSamples");
                });

            modelBuilder.Entity("Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("AI_BE.Models.Attempt", b =>
                {
                    b.HasOne("AI_BE.Models.PracticeSession", "Session")
                        .WithMany("Attempts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI_BE.Models.SignSample", "Sign")
                        .WithMany()
                        .HasForeignKey("SignId");

                    b.Navigation("Session");

                    b.Navigation("Sign");
                });

            modelBuilder.Entity("AI_BE.Models.LessonSign", b =>
                {
                    b.HasOne("Lesson", "Lesson")
                        .WithMany("LessonSigns")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("AI_BE.Models.PasswordResetToken", b =>
                {
                    b.HasOne("AI_BE.Models.Learner", "Learner")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("AI_BE.Models.PracticeSession", b =>
                {
                    b.HasOne("AI_BE.Models.Learner", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("AI_BE.Models.Learner", b =>
                {
                    b.Navigation("PasswordResetTokens");
                });

            modelBuilder.Entity("AI_BE.Models.PracticeSession", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Lesson", b =>
                {
                    b.Navigation("LessonSigns");
                });
#pragma warning restore 612, 618
        }
    }
}
